version: 2.1

references:
  deps_cache_key: &cache_key
    deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
  working_directory: &working_directory
    ~/app
  workspace: &attach_workspace
    attach_workspace:
      at: *working_directory

executors:
  node-executor:
    working_directory: *working_directory
    docker:
      - image: circleci/node:10.16.3

jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Install dependencies.
          command: yarn install
      - save_cache:
          key: *cache_key
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: *working_directory
          paths:
            - .
  lint:
    executor: node-executor
    steps:
      - *attach_workspace
      - run:
          name: Running ESLint.
          command: yarn lint
  test:
    executor: node-executor
    steps:
      - *attach_workspace
      - run:
          name: Run test suite.
          command: yarn test

workflows:
  version: 2.1
  lint_and_test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
